const getDalleResponse = require('./dalle')
const getDavinciResponse = require('./davinci')

const commands = async (message) => {
    const iaCommands = {
        davinci3: "/bot",
        dalle: "/img",
    }
    let firstWord = message.body.substring(0, message.body.indexOf(" "))
    
    const sender = message.from.includes(PHONE_NUMBER) ? message.to : message.from
    switch (firstWord) {
        case iaCommands.davinci3:
            const question = message.body.substring(message.body.indexOf(" "));
            getDavinciResponse(question).then(async (response) => {
                const contact = await message.getContact()
                client.sendMessage(sender, `${response}\n\n_Generated by @${contact.id.user}_`, { mentions: [contact] })
            })
            break

        case iaCommands.dalle:
            const imgDescription = message.body.substring(message.body.indexOf(" "));
            const contact = await message.getContact();
            getDalleResponse(imgDescription, message).then(async (imgUrl)  => {
                const media = await MessageMedia.fromUrl(imgUrl)
                // Caso queira mandar como Sticker, acrescente em options -> sendMediaAsSticker: true
                const options = {
                    mentions: [contact], 
                    caption: `_Generated by @${contact.id.user}_`, 
                    media: media,
                }
                await client.sendMessage(sender, media, options)
            })
            break
    }
}


module.exports = commands